// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG2ucYgZO_ESpzj6n25BZM2PT59vo80yo',
    appId: '1:146502102456:web:f4514a599de905fea4b34d',
    messagingSenderId: '146502102456',
    projectId: 'notefear',
    authDomain: 'notefear.firebaseapp.com',
    storageBucket: 'notefear.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJVDceeytgD_7lLucvp9QP1kFlE9NmNk',
    appId: '1:146502102456:android:c58ddc4d14a35bc0a4b34d',
    messagingSenderId: '146502102456',
    projectId: 'notefear',
    storageBucket: 'notefear.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYV5HazRsV4vRE7FfsgouLT7FuI4Mlv4M',
    appId: '1:146502102456:ios:0ad431d5d44b2d0da4b34d',
    messagingSenderId: '146502102456',
    projectId: 'notefear',
    storageBucket: 'notefear.appspot.com',
    iosClientId: '146502102456-3fvrqpap538ue3b1cvbqol5la0p5no2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.notefear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYV5HazRsV4vRE7FfsgouLT7FuI4Mlv4M',
    appId: '1:146502102456:ios:0ad431d5d44b2d0da4b34d',
    messagingSenderId: '146502102456',
    projectId: 'notefear',
    storageBucket: 'notefear.appspot.com',
    iosClientId: '146502102456-3fvrqpap538ue3b1cvbqol5la0p5no2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.notefear',
  );
}
